name = input("giorgi: ")
surname = input("gachechiladze: ")
age = input("15: ")
number1 = input("14: ")
number2 = input("16: ")

print (name)
print (surname)
print (age)
print (number1)
print (number2)